version: '3'
services:

  mariadb:
    #image: mariadb:10.3-bionic
    image: mariadb:5.5
    container_name: mariadb
    #restart: always
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: Texas0071!
      MYSQL_DATABASE: amina
    ports:
      - 3306:3306
    volumes:
     - "./db/init:/docker-entrypoint-initdb.d"

  app:
    #php:7.2-apache-stretch
    build: ./app
    container_name: app
    environment:
      TZ: "Asia/Tokyo"
      DEVELOP: "true"
    ports:
      - 80:80
      - 443:443
    links:
      - mariadb:mydb
    volumes:
      - ~/git:/var/www/html
      #- ./app/config:/usr/local/etc/php
  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
  #mysql:
  #  image: mysql:5.7
  #  environment:
  #    MYSQL_ROOT_PASSWORD: yourpasswd
  #    MYSQL_USER:     youruser
  #    MYSQL_PASSWORD: userpasswd
  #  ports:
  #    - 3306:3306
