version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    image: wordpress
    #mem_limit: 268435456
    ports:
      - "8080:80"
    links:
      - wp_db
    
  wp_db:
    #image: mariadb:10.3-bionic
    image: mariadb:5.5
    container_name: wp_db
    #restart: always
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: Texas0071!
      MYSQL_DATABASE: wordpress
    ports:
      - 3307:3306
    volumes:
     - "./db/init:/docker-entrypoint-initdb.d"
