FROM centos:centos7
#RUN yum update \
RUN yum install -y wget vim
    #&& docker-php-ext-install opcache mbstring zip mysqli pdo_mysql gd \
#    && yum clean \
#    && mkdir /var/log/php && chmod 777 /var/log/php
#composer install
#RUN curl -sS https://getcomposer.org/installer | php \
#    && mv composer.phar /usr/local/bin/composer
#xdebug install
#RUN pecl install xdebug \
#    && docker-php-ext-enable xdebug
CMD ["/sbin/init"]